type = "pod"

run-cmd=["/docker-entrypoint.sh","nginx", "-g", "daemon off;"]
run-writable-file-system = true
apply-variables-on-files = ["/etc/nginx/conf.d/default.conf"]

[build]
type = "script"
script ="""
    FROM nginx:1.25.3-alpine3.18-slim
    COPY nginx-domain-proxy/default.conf  /etc/nginx/conf.d
    """

[expose.80]
type = "http"

[variables]
EP_FIX_ENV = "/etc/nginx/conf.d/default.conf"
FRONT_DOMAIN = ""
BACK_DOMAIN = ""
BACK_URL = ""
