type = "pod"

run-cmd = ["MailHog"]

[build]
type = "image"
image = "mailhog/mailhog:v1.0.1"

[expose.1025]
# type = "tcp"
type = "tcp-node-port"
probe.disable = true

[expose.8025]
# type = "tcp"
# probe.disable = true
type = "http"

[variables]
MH_HOSTNAME = "mailhog"