type = "pod"
run-cmd = ["docker-entrypoint.sh", "mariadbd"]

[build]
type = "image"
image ="mariadb:latest"

[variables]
MYSQL_ROOT_PASSWORD.secret = true
MYSQL_PASSWORD.secret = true
MYSQL_DATABASE = "app"
MYSQL_USER = "aiohttp-sqlalchemy"

[expose.3306]
type = "tcp"

[storage."/var/lib/mysql"]
type = "block"
max-size-mb = 20000