type = "pod"
description = "X-Wiki"
run-cmd = ["/usr/local/bin/docker-entrypoint.sh", "xwiki"]
run-writable-file-system = true
cpu = 400
ram = 8000

[build]
type = "image"
image ="xwiki:14.4.1-postgres-tomcat"



# run-cmd = ["sleep", "999999"]

[variables]
DB_HOST = "postgresql"
DB_PORT = "5432"
DB_USER = "{{postgresql.POSTGRES_USER}}"
DB_PASSWORD = "{{postgresql.POSTGRES_PASSWORD}}"
LOG_FORMAT="%time{23} [%thread%] %level% %message%"
DB_DATABASE = "xwiki"
PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/tomcat/bin"

[expose.8080]
type = "http"
[expose.8080.probe]
disable = true

[storage."/usr/local/xwiki/data"]
type = "block"
max-size-mb = 2000

[storage."/usr/local/tomcat/log"]
type = "block"
max-size-mb = 500
