type = "pod"

run-writable-file-system = true
run-cmd = ["/entrypoint.sh"]

[build]
type = "image"
image = "dpage/pgadmin4:6.20"

[variables]
PGADMIN_DEFAULT_EMAIL = "test@timoni.dev"
PGADMIN_DEFAULT_PASSWORD.secret = true

[expose.80]
type = "http"
