type = "pod"
run-cmd = ["/docker-entrypoint.sh", "apache2-foreground"]
run-writable-file-system = true
[build]
type = "image"
image ="roundcube/roundcubemail:1.6.0-apache"
[variables]
ROUNDCUBEMAIL_DEFAULT_HOST = "tls://mail.timoni.io"
ROUNDCUBEMAIL_DEFAULT_PORT = "143"
ROUNDCUBEMAIL_SMTP_SERVER = "tls://mail.timoni.io"
ROUNDCUBEMAIL_SMTP_PORT = "587"
ROUNDCUBEMAIL_DB_TYPE = "sqlite"
# ENV_ID = ""
# ROUNDCUBEMAIL_DEFAULT_HOST = "tls://maddy.{{ENV_ID}}.svc"

[expose.80]
type = "http"
probe.disable = true

# [storage."/var/roundcube/config"]
# type = "block"
# max-size-mb = 1000

[storage."/var/roundcube/db"]
type = "block"
max-size-mb = 1000
