type = "pod"
description = "Kibana"

run-writable-file-system = true
run-as-user = [1000]
run-cmd = [ "/usr/local/bin/kibana-docker" ]

[build] 
type = "image"
image = "docker.elastic.co/kibana/kibana:8.4.1"

[variables]
ELASTICSEARCH_HOSTS = "http://elasticsearch-es-http:9200"

[expose.5601]
type = "http"