type = "pod"
description = "Kibana"

build = "FROM docker.elastic.co/kibana/kibana:8.4.1"
run-writable-file-system = true

run-as-user = [1000]
run-cmd = [ "/usr/local/bin/kibana-docker" ]


[variables]
ELASTICSEARCH_HOSTS = "http://elasticsearch-es-http:9200"

[expose.5601]
type = "http"