type = "domain"

names = ["{{DOMAIN_NAME}}"]
include-elements = ["{{SERVICE_NAME}}"]

[inputs]
SERVICE_NAME.type = "text"
SERVICE_NAME.message = "Name of service for which custom domain will be set"
DOMAIN_NAME.type = "text"
DOMAIN_NAME.message = "Name of domain for service"
