type = "pod"

run-cmd = ["/etc/confluent/docker/run"]
run-writable-file-system = true

[build]
type = "image"
image = "confluentinc/cp-kafka:7.3.0"

[expose."19092"]
type = "tcp"
[expose.19092.probe]
disable = true

[expose."9092"]
type = "tcp"
[expose.9092.probe]
disable = true

[variables]
KAFKA_ADVERTISED_LISTENERS = "INTERNAL://kafka:19092,EXTERNAL://{{CLUSTER_DOMAIN}}:9092"
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP = "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
KAFKA_INTER_BROKER_LISTENER_NAME = "EXTERNAL"
KAFKA_ZOOKEEPER_CONNECT = "zookeeper:2181"
KAFKA_BROKER_ID = 1
KAFKA_LOG4J_LOGGERS = "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR = 1
KAFKA_JMX_PORT = 9999
KAFKA_JMX_HOSTNAME = "localhost"
KAFKA_AUTHORIZER_CLASS_NAME = "kafka.security.authorizer.AclAuthorizer"
KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND = true
