organization:
  name: "org"

clusters:
  - id: default
    name: KafkaDevelopmentCluster
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    schemaRegistry:
      url: "$SR_SERVER"
      ignoreUntrustedCertificate: false

auth:
  demo-users:
    - email: "${CDK_ADMIN_EMAIL}"
      password: "${CDK_ADMIN_PASSWORD}"
      groups:
        - ADMIN
