type = "pod"
description = "Grafana 9"

run-cmd = ["/run.sh"]
run-writable-file-system = true

[build]
type = "script"
script = """
    FROM grafana/grafana:9.0.4

    RUN grafana-cli plugins install grafana-piechart-panel

    COPY grafana/grafana.ini /etc/grafana
    COPY grafana/provisioning /etc/grafana/provisioning
    COPY grafana/dashboards /etc/grafana/dashboards
"""

[variables]
PATH = "/usr/share/grafana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
GF_SECURITY_ADMIN_PASSWORD.type = "secret"

[expose.3000]
type = "http"


