type = "pod"

build ="""
    FROM lmenezes/cerebro
    USER cerebro
"""
run-writable-file-system = true
run-as-user = [1000] # cerebro
run-cmd = ["/opt/cerebro/bin/cerebro"]

[expose.9000]
type = "http-domain"