type = "pod"

# run-cmd = ["sleep", "infinity"]
run-cmd = ["/assets/wrapper"]
run-writable-file-system = true

[build]
type = "image"
image = "gitlab/gitlab-ce:16.3.1-ce.0"

[storage.'/var/opt/gitlab']
type = 'block'
max-size-mb = 10_000 # 10 GB

[storage.'/etc/gitlab']
type = 'block'
max-size-mb = 100 # MB

[storage.'/dev/shm']
type = 'temp'
max-size-mb = 200 # MB

[expose.80]
type = 'http'
probe.disable = true

# [expose.22]
# type = 'tcp'
# probe.disable = true

# [variables]
# cat /etc/gitlab/initial_root_password
