type='pod'
build='''
    FROM ubuntu/squid:latest
    COPY squid/squid.conf /etc/squid/squid.conf
    
'''
run-cmd=["entrypoint.sh"]
run-writable-file-system=true
[expose.3128]
type='tcp-internal'
probe.disable=true

[storage.'/var/log/squid']
type='temp'
max-size-mb=100
[storage.'/var/spool/squid']
type='block'
max-size-mb=900

