type='pod'
run-cmd=["entrypoint.sh"]
run-writable-file-system=true
[build]
type = "script"
script = """
    FROM ubuntu/squid:latest
    COPY squid/squid.conf /etc/squid/squid.conf
"""
[expose.3128]
type='tcp'
probe.disable=true

[storage.'/var/log/squid']
type='temp'
max-size-mb=100
[storage.'/var/spool/squid']
type='block'
max-size-mb=900

