type = "pod"

build = """
FROM foxcpp/maddy:0.6.2
"""

run-cmd = ["/bin/maddy", "-config", "/config/maddy.conf", "run"]

run-writable-file-system = true

[variables]
MADDY_HOSTNAME.type = "text"
MADDY_DOMAIN.type = "text"
MADDY_CONFIG = "/config/maddy.conf"

[expose.25]
# SMTP
type = "ip-external"
probe.disable = true
name = "maddy-external"

[expose.465]
# TLS SMTP
type = "tcp"
probe.disable = true

[expose.587]
# STARTTLS SMTP
type = "ip-external"
probe.disable = true
name = "maddy-external"

[expose.143]
# None/STARTTLS IMAP
type = "ip-external"
probe.disable = true
name = "maddy-external"

[expose.993]
# TLS IMAP
type = "tcp"
probe.disable = true

[storage."/data"]
type = "block"
max-size-mb = 1000
