type = "pod"

run-cmd = ["/bin/maddy", "-config", "/config/maddy.conf", "run"]
run-writable-file-system = true

[build]
type = "image"
image = "foxcpp/maddy:0.6.2"

[variables]
MADDY_HOSTNAME = ""
MADDY_DOMAIN = ""
MADDY_CONFIG = "/config/maddy.conf"

[expose.25]
# SMTP
type = "ip-external"
probe.disable = true
name = "maddy-external"

[expose.465]
# TLS SMTP
type = "tcp"
probe.disable = true

[expose.587]
# STARTTLS SMTP
type = "ip-external"
probe.disable = true
name = "maddy-external"

[expose.143]
# None/STARTTLS IMAP
type = "ip-external"
probe.disable = true
name = "maddy-external"

[expose.993]
# TLS IMAP
type = "tcp"
probe.disable = true

[storage."/data"]
type = "block"
max-size-mb = 1000
