type = "pod"

run-cmd = ["docker-entrypoint.sh", "mongod"]
run-writable-file-system = true

[build]
type = "image"
image = "mongo:6.0.2"

[variables]
MONGO_INITDB_ROOT_USERNAME.type = "text"
MONGO_INITDB_ROOT_PASSWORD.secret = true
MONGO_INITDB_DATABASE.type = "text"


[storage."/data"]
type = "block"
max-size-mb = 2000

[storage."/var/log/mongodb"]
type = "block"
max-size-mb = 1000

[storage."/var/run"]
type = "temp"
max-size-mb = 10

[storage."/tmp"]
type = "temp"
max-size-mb = 40