type = "pod"
run-cmd = ["/app"]
run-writable-file-system = true

[build]
type = "script"
script = """
FROM golang:1.21.3-alpine3.18 as build
COPY ingress/redirect-domain/main.go /src
COPY ingress/redirect-domain/go.mod /src
RUN cd /src && go build -o redirect

FROM alpine:3.18
COPY --from=build /src/redirect /app
"""

[variables]
TARGET_URL = ""
TARGET_PATH = ""

[expose.80]
type = "http"
probe.disable = true
