type = 'pod'
run-writable-file-system = true
run-cmd = ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
[build]
type = 'script'
script = """
FROM python:3.11.1-bullseye
RUN python -m pip install Django
RUN django-admin startproject app
WORKDIR /app
COPY django1/settings.py ./app/
"""
[expose.8000]
type = 'http'
