type = "pod"

# run-cmd = ["sleep", "infinity"]
run-cmd = ["/docker-entrypoint.sh", "apache2-foreground"]
run-writable-file-system = true

[build]
type = "image"
image = "phpmyadmin/phpmyadmin:5.2.1"
# https://hub.docker.com/_/phpmyadmin

[expose.80]
type = "http"

[variables]
PMA_HOST = "mariadb"
PMA_USER = "{{mariadb.MARIADB_ROOT_USER}}"
PMA_PASSWORD = "{{mariadb.MYSQL_ROOT_PASSWORD}}"
MEMORY_LIMIT = "200M"
UPLOAD_LIMIT = "100M"
MAX_EXECUTION_TIME = "600" # sec
