type = "pod"

# run-cmd = ["sleep", "infinity"]
run-cmd = ["/docker-entrypoint.sh", "apache2-foreground"]
run-writable-file-system = true

[build]
type = "image"
image = "phpmyadmin/phpmyadmin:5.2.1"

[expose.80]
type = "http"

[variables]
PMA_HOST = "mysql"
PMA_USER = "root"
PMA_PASSWORD = "{{mysql.MYSQL_ROOT_PASSWORD}}"
