type = "pod"

run-cmd = [
    "/bin/bash", "-c",
    """
    "cp -ruT /activemq_files/data /data/activemq &&
    cp -ruT /activemq_files/conf /opt/activemq/conf &&
    rm -r /activemq_files &&
    /app/run.sh"
    """
    ]
run-writable-file-system = true

[build] 
type = "script"
script = """
    FROM webcenter/activemq:5.14.3
    RUN mkdir /activemq_files
    RUN cp -r /data/activemq /activemq_files/data
    RUN cp -r /opt/activemq/conf /activemq_files/conf
    """

[variables]
ACTIVEMQ_ADMIN_LOGIN.type = "text"
ACTIVEMQ_ADMIN_PASSWORD.type = "secret"

[expose.8161]
type = "http"

[expose.1883]
type = "tcp"
probe.disable = true

[expose.5672]
type = "tcp"
probe.disable = true

[expose.61613]
type = "tcp"
probe.disable = true

[expose.61614]
type = "tcp"
probe.disable = true

[expose.61616]
type = "tcp"
probe.disable = true

[storage."/data/activemq"]
type = "block"
max-size-mb = 2000

[storage."/var/log/activemq"]
type = "block"
max-size-mb = 1000

[storage."/opt/activemq/conf"]
type = "block"
max-size-mb = 200