type = "pod"
build = """
    FROM postgres:14.2-alpine
    COPY update_pg_access.sh /docker-entrypoint.d
    """

run-cmd = ["docker-entrypoint.sh", "postgres"]

[expose.5432]
type = "tcp"

[variables]
POSTGRES_USER = "{{PGUSER}}"
POSTGRES_DB = "xwiki"
PGUSER = "postgres"
PGDATA = "/var/lib/postgresql/pgdata"

[variables]
POSTGRES_ROOT_PASSWORD.secret = true
POSTGRES_PASSWORD.secret = true

[storage."/var/lib/postgresql"]
type = "block"
max-size-mb = 2000

[storage."/etc/postgresql"]
type = "block"
max-size-mb = 500

[storage."/var/log/postgresql"]
type = "block"
max-size-mb = 2000

[storage."/var/run"]
type = "temp"
max-size-mb = 10

[storage."/tmp"]
type = "temp"
max-size-mb = 40
