type='pod'

run-cmd=['/entrypoint.sh','arangod']
run-writable-file-system=true

[build]
type = "image"
image = "arangodb:3.9.4"

[variables]
ARANGO_ROOT_PASSWORD.type = "secret"

[expose.8529]
type='http'

[storage.'/var/lib/arangodb3']
type='block'
max-size-mb=1000

[storage.'/var/lib/arangodb3-apps']
type='block'
max-size-mb=1000