type = "pod"
run-cmd = [ "/usr/local/bin/docker-entrypoint.sh", "apache2-foreground" ]
run-writable-file-system = true

[build]
type = "script"
script = """
FROM wordpress:6
RUN cp $PHP_INI_DIR/php.ini-production  $PHP_INI_DIR/php.ini
RUN sed 's|post_max_size = 8M|post_max_size = 100M|g' -i $PHP_INI_DIR/php.ini
RUN sed 's|upload_max_filesize = 2M|upload_max_filesize = 100M|g' -i $PHP_INI_DIR/php.ini
"""

[variables]
WORDPRESS_DB_HOST = "mysql"
WORDPRESS_DB_USER = "{{mysql.MYSQL_USER}}"
WORDPRESS_DB_NAME = "{{mysql.MYSQL_DATABASE}}"
WORDPRESS_TABLE_PREFIX = "wp_"
WORDPRESS_DB_PASSWORD.secret = true
WORDPRESS_DB_PASSWORD.value = "{{mysql.MYSQL_PASSWORD}}"

[storage."/var/www/html"]
type = "block"
max-size-mb = 6000

[expose.80]
type = "http"
probe.disable = true
