type = "pod"
run-cmd = [ "/usr/local/bin/docker-entrypoint.sh", "apache2-foreground" ]
run-writable-file-system = true

[build]
type = "script"
script = """
FROM wordpress:6.3-php8.1-apache
RUN cp $PHP_INI_DIR/php.ini-production  $PHP_INI_DIR/php.ini

# max upload size
RUN sed 's|post_max_size = 8M|post_max_size = 100M|g' -i $PHP_INI_DIR/php.ini
RUN sed 's|upload_max_filesize = 2M|upload_max_filesize = 100M|g' -i $PHP_INI_DIR/php.ini

# ionCube Loader for PHP
RUN sed 's|zend_extension=opcache|zend_extension=opcache\\nzend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20200930/ioncube_loader_lin_8.1.so|g' -i $PHP_INI_DIR/php.ini
ADD wordpress/ioncube_loader_lin_8.1.so  /usr/local/lib/php/extensions/no-debug-non-zts-20200930
"""

[variables]
WORDPRESS_DB_HOST = "mysql"
WORDPRESS_DB_USER = "{{mysql.MYSQL_USER}}"
WORDPRESS_DB_NAME = "{{mysql.MYSQL_DATABASE}}"
WORDPRESS_TABLE_PREFIX = "wp_"
WORDPRESS_DB_PASSWORD.secret = true
WORDPRESS_DB_PASSWORD.value = "{{mysql.MYSQL_PASSWORD}}"

[storage."/var/www/html"]
type = "block"
max-size-mb = 6000

[expose.80]
type = "http"
probe.disable = true
