type = "pod"
run-cmd = ["/usr/local/bin/docker-entrypoint.sh", "apache2-foreground"]
run-writable-file-system = true

[build]
type = "script"
script = """
FROM wordpress:6-php7.4-apache
RUN cp $PHP_INI_DIR/php.ini-production  $PHP_INI_DIR/php.ini

# max upload size
RUN sed 's|post_max_size = 8M|post_max_size = 100M|g' -i $PHP_INI_DIR/php.ini
RUN sed 's|upload_max_filesize = 2M|upload_max_filesize = 100M|g' -i $PHP_INI_DIR/php.ini

# ionCube Loader for PHP
RUN sed 's|extension=xsl|extension=xsl\\nzend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20190902/ioncube_loader_lin_7.4.so|g' -i $PHP_INI_DIR/php.ini
ADD wordpress/ioncube_loader_lin_7.4.so  /usr/local/lib/php/extensions/no-debug-non-zts-20190902

# soap
RUN apt update && apt install -y libxml2-dev
RUN docker-php-ext-install soap

# locales
RUN apt install -y locales
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
"""

[variables]
WORDPRESS_DB_HOST = "mariadb"
WORDPRESS_DB_USER = "{{mariadb.MARIADB_USER}}"
WORDPRESS_DB_NAME = "{{mariadb.MARIADB_DATABASE}}"
WORDPRESS_TABLE_PREFIX = "wp_"
WORDPRESS_DB_PASSWORD.secret = true
WORDPRESS_DB_PASSWORD.value = "{{mariadb.MARIADB_PASSWORD}}"
LANG = "pl_PL.UTF-8"

[storage."/var/www/html"]
type = "block"
max-size-mb = 6000

[expose.80]
type = "http"
probe.disable = true
