type = "pod"
run-cmd = [ "/usr/local/bin/docker-entrypoint.sh", "apache2-foreground" ]
run-writable-file-system = true

[build]
type = "image"
image ="wordpress:6"

[variables]
WORDPRESS_DB_HOST = "mysql"
WORDPRESS_DB_USER = "{{mysql.MYSQL_USER}}"
WORDPRESS_DB_NAME = "{{mysql.MYSQL_DATABASE}}"
WORDPRESS_TABLE_PREFIX = "wp_"
WORDPRESS_DB_PASSWORD.type = "secret"
WORDPRESS_DB_PASSWORD.value = "{{mysql.MYSQL_PASSWORD}}"

[storage."/var/www/html"]
type = "block"
max-size-mb = 6000

[expose.80]
type = "http"
