type = "pod"

run-cmd = ["python", "manage.py", "runserver", "0.0.0.0:8000"]
run-writable-file-system = true

[build]
type = "script"
script = """
FROM python:3
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY example/manage.py /code/manage.py
COPY example/example /code/example
"""


[variables]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
POSTGRES_NAME = "{{postgres.POSTGRES_DB}}"
POSTGRES_USER = "{{postgres.POSTGRES_USER}}"
POSTGRES_PASSWORD.secret = true
POSTGRES_PASSWORD.value = "{{postgres.POSTGRES_PASSWORD}}"

[expose.8000]
type = 'http'
