type = "pod"

run-cmd = ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
run-writable-file-system = true

[build]
type = 'script'
script = """
FROM python:3.11.1-bullseye
WORKDIR /app

RUN python -m pip install 'Django>=4.0,<5.0' 'psycopg2>=2.8'
RUN django-admin startproject app /app

COPY django/settings.py /app/app
"""

[expose.8000]
type = 'http'

[variables]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
#POSTGRES_NAME = "{{postgresql.POSTGRES_DB}}"
#POSTGRES_USER = "{{postgresql.POSTGRES_USER}}"
#POSTGRES_PASSWORD = "{{postgresql.POSTGRES_PASSWORD}}"
