type = "pod"

run-cmd = ["python", "manage.py", "runserver", "0.0.0.0:8000"]
run-writable-file-system = true

[build]
type = "dockerfile"
dockerfile = '/django/.timoni-docker-file'


[variables]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
POSTGRES_NAME = "{{postgres.POSTGRES_DB}}"
POSTGRES_USER = "{{postgres.POSTGRES_USER}}"
POSTGRES_PASSWORD.type = "secret"
POSTGRES_PASSWORD.value = "{{postgres.POSTGRES_PASSWORD}}"

[expose.8000]
type = 'http'