type='pod'

build='''
FROM varnish:latest
COPY varnish/default.vcl /etc/varnish/
'''

run-cmd=['/usr/local/bin/docker-varnish-entrypoint']

[storage.'/var/lib/varnish']
type='temp'
max-size-mb=100

[expose.80]
type='http'

[expose.8443]
type='tcp'
probe.disable=true
