type = 'pod'

run-cmd = ['/usr/local/bin/docker-varnish-entrypoint']
apply-variables-on-files = ["/etc/varnish/default.vcl"]
run-writable-file-system = true

[build]
type = "script"
script = """
    FROM varnish:7.3.0
    COPY varnish/default.vcl /etc/varnish/
    COPY varnish/prometheus_varnish_exporter-1.6.1.linux-amd64/prometheus_varnish_exporter /
    """

[storage.'/var/lib/varnish']
type = 'temp'
max-size-mb = 100

[expose.80]
type = 'http'
probe.disable = true

[expose.8443]
type = 'tcp'
probe.disable = true

[expose.9131] # metrics
type = 'http-internal'
metrics-path = "/metrics"
probe.disable = true

[variables]
BackendPort = "80"
BackendDomain = "wordpress"
