type = "container"

build ="FROM mariadb"
run-cmd=["docker-entrypoint.sh","mariadbd"]
run-writable-file-system=true

[expose.3306]
type ="tcp-internal"

[inputs]
MARIADB_USER.type = "text"
MARIADB_USER.message = "Name of database user"
MARIADB_PASSWORD.type = "secret"
MARIADB_PASSWORD.message = "Password or user"
MARIADB_ROOT_PASSWORD.type = "secret"
MARIADB_ROOT_PASSWORD.message = "Password of root user"

[storage."/var/lib/mysql"]
type = "block"
max-size-mb = 500

[storage."/var/log/mysql"]
type = "block"
max-size-mb = 100

#/etc/mysql
#[storage.""]
#/tmp
#[storage.""]
#/run/mysqld
