type = "pod"

run-cmd = ["docker-entrypoint.sh", "mariadbd"]
run-writable-file-system = true

[build]
type = "script"
script = """
    FROM mariadb:11.0.3-jammy
    RUN apt update && apt install mysqltuner
    """

[variables]
MARIADB_DATABASE = "db"

MARIADB_USER = "db"
MARIADB_PASSWORD.secret = true

MARIADB_ROOT_USER = "mysql"
MARIADB_ROOT_PASSWORD.secret = true


[expose.3306]
type = "tcp"

[storage."/var/lib/mysql"]
type = "block"
max-size-mb = 500

[storage."/var/log/mysql"]
type = "block"
max-size-mb = 100
