type = "pod"

run-cmd=["docker-entrypoint.sh","mariadbd"]
run-writable-file-system=true

[build] 
type = "image"
image = "mariadb"

[expose.3306]
type ="tcp"

[variables]
USER = ""
PASSWORD.secret = true
MARIADB_ROOT_PASSWORD.secret = true

[storage."/var/lib/mysql"]
type = "block"
max-size-mb = 500

[storage."/var/log/mysql"]
type = "block"
max-size-mb = 100

#/etc/mysql
#[storage.""]
#/tmp
#[storage.""]
#/run/mysqld
