type = "pod"

# run-writable-file-system = true
# run-cmd = ["sleep", "999999"]
# run-as-user = [10001]
run-cmd = ["/opt/mssql/bin/sqlservr"]

[build] 
type = "script"
script = """
FROM mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04

USER root
# RUN groupadd -g 10001 mssql
# RUN mkdir -p /var/opt/mssql/data/
# RUN chown mssql:mssql -R /var/opt

# USER mssql
"""

[variables]
SA_PASSWORD = "nopCommerce_db_password"
ACCEPT_EULA = "Y"
MSSQL_PID = "Express"
MSSQL_DATA_DIR = "/var/opt/mssql/data/"
DB_NAME = "nopcommerce"
DB_USER = "nopcommerce"
DB_PASS = "{{SA_PASSWORD}}"

[expose.1433]
type = "tcp"

[storage."/var/opt/mssql/"]
type = "block"
max-size-mb = 500

[storage."/.system"]
type = "temp"
max-size-mb = 50

[storage."/log"]
type = "temp"
max-size-mb = 50
