type = "pod"

build = """
    FROM node
    WORKDIR /app
    COPY nodejs/index-1.js .
"""
run-writable-file-system = true

run-cmd = ["docker-entrypoint.sh","node", "index-1.js"]

[expose.3000]
type = "http-domain"
