type = "pod"
description = "mariadb standalone server base on Alpine"

run-cmd = ["/scripts/run.sh"]

[build]
type = "script"
script = """
COPY standalone/apk-repos /etc/apk/repositories

RUN apk update --allow-untrusted && apk upgrade --allow-untrusted
RUN apk add --allow-untrusted --no-cache mariadb mariadb-client mariadb-server-utils pwgen && rm -f /var/cache/apk/*

ADD standalone/run.sh /scripts/run.sh
RUN mkdir /docker-entrypoint-initdb.d && \\
    mkdir /scripts/pre-exec.d && \\
    mkdir /scripts/pre-init.d && \\
    rm -rf /var/tmp && \\
    ln -sf /tmp /var/tmp && \\
    chmod -R 755 /scripts

COPY standalone/my.cnf /etc
"""

[from]
git-repo-name = "alpine"
branch = "master"
commit = "68b9cb67b78358a69025de276674fdb3d9f9ca4d"
file-path = "edge"

[expose.3306]
type = "tcp"

[storage."/var/lib/mysql"]
max-size-mb = 1000
type = "block"

[storage."/run/mysqld"]
max-size-mb = 2
type = "temp"

[storage."/tmp"]
max-size-mb = 100
type = "temp"

[variables]
# MYSQL_DATABASE = "{{ELEMENT_NAME}}"
MYSQL_DATABASE = "mariadb"
MYSQL_PASSWORD = "user-pwd"
MYSQL_ROOT_PASSWORD = "cau4ooNgahc5Ooce"
MYSQL_USER = "user"
LOG_FORMAT = "%timestamp{19}% %num% [%level%] %message%"
