type = "pod"
description = "mariadb standalone server base on Alpine"

run-cmd = ["/scripts/run.sh"]

[build]
type = "script"
script = """
FROM alpine:3.18.3

RUN apk update && apk upgrade
RUN apk add --no-cache mariadb mariadb-client mariadb-server-utils pwgen && rm -f /var/cache/apk/*

ADD run.sh /scripts/run.sh
RUN mkdir /docker-entrypoint-initdb.d && \\
    mkdir /scripts/pre-exec.d && \\
    mkdir /scripts/pre-init.d && \\
    rm -rf /var/tmp && \\
    ln -sf /tmp /var/tmp && \\
    chmod -R 755 /scripts

COPY my.cnf /etc
"""

[expose.3306]
type = "tcp"

[storage."/var/lib/mysql"]
max-size-mb = 1000
type = "block"

[storage."/run/mysqld"]
max-size-mb = 2
type = "temp"

[storage."/tmp"]
max-size-mb = 100
type = "temp"

[variables]
MARIADB_DATABASE = "db"

MARIADB_USER = "db"
MARIADB_PASSWORD.secret = true

MARIADB_ROOT_USER = "mysql"
MARIADB_ROOT_PASSWORD.secret = true

LOG_FORMAT = "%timestamp{19}% %num% [%level%] %message%"
