type = "config"

[variables]
COMMON_NAME = "postal"
ROOT_PASSWORD = "{{COMMON_NAME}}"
USER_PASSWORD = "{{COMMON_NAME}}"

MYSQL_DATABASE = "{{COMMON_NAME}}"
MYSQL_PASSWORD = "{{COMMON_NAME}}"
MYSQL_ROOT_PASSWORD = "{{COMMON_NAME}}"
MYSQL_USER = "{{COMMON_NAME}}"

RABBITMQ_DEFAULT_USER = "{{COMMON_NAME}}"
RABBITMQ_DEFAULT_PASS = "{{COMMON_NAME}}"
RABBITMQ_DEFAULT_VHOST = "{{COMMON_NAME}}"

[inputs]
SMTP_DOMAIN.type = "text"
WEB_DOMAIN.type = "text"
