type = "pod"

run-cmd = ["rabbitmq-server"]

[build] 
type = "image"
image = "rabbitmq:3"

[variables]
RABBITMQ_DEFAULT_USER = "{{config.RABBITMQ_DEFAULT_USER}}"
RABBITMQ_DEFAULT_PASS = "{{config.RABBITMQ_DEFAULT_PASS}}"
RABBITMQ_DEFAULT_VHOST = "{{config.RABBITMQ_DEFAULT_VHOST}}"

[expose.5672]
type = "tcp"

[storage."/var/log"]
type= "block"
max-size-mb = 500
