type = "pod"
run-cmd = ["docker-entrypoint.sh", "redis-server"]
run-writable-file-system=true
[build]
type = "image"
image ="redis"
[expose.6379]
type = "tcp"

[storage."/tmp"]
type = "block"
max-size-mb = 100

[storage."/data"]
type = "block"
max-size-mb = 100