type = "pod"
run-cmd = ["docker-entrypoint.sh", "mysqld"]

[build]
type = "image"
image ="mysql:8.0"

[variables]
MYSQL_ROOT_PASSWORD.type = "secret"
MYSQL_PASSWORD.type = "secret"
MYSQL_DATABASE = "db"
MYSQL_USER = "user"

[expose.3306]
type = "tcp"

[storage."/tmp"]
type = "temp"
max-size-mb = 20

[storage."/var/run/mysqld"]
type = "temp"
max-size-mb = 20

[storage."/var/lib/mysql"]
type = "block"
max-size-mb = 1000
