type = "container"
description = "Browserless Chrome"

build = "FROM browserless/chrome:1.56.0-puppeteer-18.0.5"
run-writable-file-system = true
run-cmd = [ "/usr/src/app/start.sh" ] 

[expose.3000]
type = "http-domain"