type = "pod"
description = "Selenium firefox"
run-writable-file-system = true
run-cmd = [ "/opt/bin/entry_point.sh" ]
[build]
type = "image"
image ="selenium/standalone-firefox:4.5.3-20221024"
[variables]
SE_VNC_NO_PASSWORD = "1"


[expose.4444]
type = "http"

[expose.7900]
type = "http"
probe.disable = true